### ISSUE TITLE
Use Desktop API Key

### ISSUE THREAD

**Issue by steveoh** [scottriding/utah_legislators_api#1]
There is no need to [spoof the referring url](https://github.com/scottriding/utah_legislators_api/blob/master/models/utah_address.rb#L34). Instead, create an ip based server api key and win!

**Comment by scottriding** [comment]
This is a good point.

I'm currently hosting with Heroku, so I have to [pay extra](https://addons.heroku.com/proximo) for a static IP. But for anyone who hosts this on a box, this makes sense. Does it bother you guys that it is spoofed here?

**Comment by steveoh** [comment]
Nope, sometimes people just do not seem to realize how that was designed to
work.
